name: zig CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    name: Build and Test
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0-dev.70+73a0b5441
      - run: zig build
      - run: zig build -Dtarget=x86_64-linux
